services:
  rtb-app:
    container_name: "rtb-local"
    ports: ["8080:8080"]  # expose app to your Mac
    environment:
      KAFKA_BOOTSTRAP: kafka:29092
      # Use HOST port binding for ClickHouse & Kafka
      CLICKHOUSE_URL: jdbc:ch://host.docker.internal:8123/default?async_insert=1&wait_for_async_insert=0&compress=1&decompress=1&socket_timeout=5000&connection_timeout=3000

      # If your bidders are on your Mac too, also use the host
      EXTERNAL_TARGETS: "http://localhost:9100/bid,http://localhost:9101/bid,http://localhost:9102/bid,http://localhost:9103/bid,http://localhost:9104/bid"