services:
  rtb-app:
    container_name: rtb-local
    ports: ["8080:8080"]
    # no host network on Mac
    environment:
      # Kafka & ClickHouse are compose services → use service names
      KAFKA_BOOTSTRAP: kafka:29092
      CLICKHOUSE_URL: jdbc:ch://clickhouse:8123/default?async_insert=1&wait_for_async_insert=0&compress=1&decompress=1&socket_timeout=5000&connection_timeout=3000

      # If your bidders run on your Mac (outside Docker), use host.docker.internal
      # If you dockerize bidders too, use their service names instead.
      EXTERNAL_TARGETS: "http://host.docker.internal:9100/bid,http://host.docker.internal:9101/bid,http://host.docker.internal:9102/bid,http://host.docker.internal:9103/bid,http://host.docker.internal:9104/bid"